- name: Setup kernel parameters for better performance
  hosts: all
  gather_facts: false
  tasks:
  - name: Create grub file
    copy:
      dest: /etc/default/grub.d/90-cmdlinux.cfg
      content: GRUB_CMDLINE_LINUX="processor.max_cstate=1 intel_idle.max_cstate=0"
      mode: 0644
    notify: update grub
  handlers:
    - name: Update grub file
      command: grub-mkconfig -o /boot/grub/grub.cfg
      listen: update grub
    - name: Reboot system
      reboot:
        reboot_timeout: 300
        msg: "Reboot initiated by Ansible for kernel parameter change"
      listen: update grub
