- name: Configure network interfaces for Ubuntu 20.04
  hosts: all
  vars:
    # variable flag for falling if there is more than one interface in the system
    # because we should use active interface and it could be cnanged if we will use another interface for ssh connection
    # if you want to skip this check, set this variable to true
    skip_interface_check: false
  tasks:
    - name: Check if system is Ubuntu
      assert:
        that:
          - distribution == 'Ubuntu'
          - distribution_version == '20.04'
        msg: "This playbook is only for Ubuntu"
    - name: Check if there is more than one interface except lo
      assert:
        that:
          - ansible_interfaces|reject('match', 'lo')|length == 1 or skip_interface_check
        msg: "There is more than one interface in the system"
    - name: Create netplan config file
      copy:
        dest: /etc/netplan/01-netcfg.yaml
        content: |
          network:
            version: 2
            ethernets:
              net0:
                dhcp4: true
                dhcp6: false
                match:
                  macaddress: "{{ ansible_default_ipv4.macaddress }}"
                set-name: net0
      notify: restart netplan
    - name: Delete cloud init network config file
      file:
        path: /etc/netplan/50-cloud-init.yaml
        state: absent
      notify: restart netplan
    - name: Flush handlers
      meta: flush_handlers
    - name: Wait for connection
      wait_for_connection:
        delay: 10
        timeout: 300
    - name: Gather facts about the renamed interface
      gather_facts:

    - name: Display information about the renamed interface
      debug:
        var: ansible_interfaces

  handlers:
    - name: Check netplan config
      command: netplan generate
      listen: restart netplan
    - name: Apply netplan config
      command: netplan apply
      listen: restart netplan
